% ---------------------------------------------------------------------
\title{Brain Visualization - STAR Report}

% for anonymous conference submission please enter your SUBMISSION ID
% instead of the author's name (and leave the affiliation blank) !!
\author[M.  \& M. Konefal]
       {M. $^{1}$
        and M. Konefal$^{1}$
        \\
         $^1$Group ?\\
       }

% ------------------------------------------------------------------------

% if the Editors-in-Chief have given you the data, you may uncomment
% the following five lines and insert it here
%
% \volume{27}   % the volume in which the issue will be published;
% \issue{1}     % the issue number of the publication
% \pStartPage{1}      % set starting page
% ------------------------------------------------------------------------


\begin{document}

\maketitle

%-------------------------------------------------------------------------
\begin{abstract}

Abstract.

\end{abstract}

%-------------------------------------------------------------------------
\section{Introduction}

Cite something\cite{Murre-Sturdy95}. 

%-------------------------------------------------------------------------
\subsection{Subsection 1.1}


%-------------------------------------------------------------------------
\section{Section 2}


%-------------------------------------------------------------------------

\section{Responsibilities}


%-------------------------------------------------------------------------
\bibliography{egbibsample}
\bibliographystyle{eg-alpha}
%\bibliographystyle{eg-alpha-doi}

\end{document}
